version: "3"
services:
  web:
    build:
      context: ../example-soa-web
    command: npm run dev
    depends_on: [api]
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
  api:
    build:
      context: ../example-soa-api
    command: npm run start
    environment:
      PORT: 3001
    ports:
      - "3001:3001"
