version: "3"
services:
  web:
    build:
      context: ../example-soa-web
    command: npm run dev
    depends_on: [api]
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ../example-soa-web:/workspace
      # Workaround: Prevent host `node_modules` from being mounted.
      - notused_web:/workspace/node_modules
  api:
    build:
      context: ../example-soa-api
    command: npm run start
    environment:
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ../example-soa-api:/workspace
      # Workaround: Prevent host `node_modules` from being mounted.
      - notused_api:/workspace/node_modules
volumes:
  # Workaround: Prevent host `node_modules` from being mounted.
  notused_web:
  notused_api:
